image: ivobos/js-mobile-game-quickstart-ci-image:0.0.4

pipelines:
  tags:
    v*:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run cordova:prepare
            - npm run android

options:
  docker: true
